title: Dinaria API Docs
description: Documentation for the Dinaria payment API
remote_theme: just-the-docs/just-the-docs
color_scheme: dinaria
search_enabled: true
logo: /assets/images/dinaria-logo.png
custom_css: custom
aux_links:
  "API Spec (OpenAPI)": https://dinariap.github.io/dinaria-api-docs/paymentAPI.yaml
  "Dinaria": https://dinaria.com
footer_content: "© 2026 Dinaria · support@dinaria.com"
plugins:
  - jekyll-remote-theme
  - jekyll-include-cache
